### ISSUE TITLE
Channel Islands example throws "Looping" error if join ID property not specified

### ISSUE THREAD

**Issue by twelch** [seasketch/union-subdivided-polygons#5]
## Expected Behavior
If you don't specify an `originalIdProperty` the union can still be performed, just slower.

## Actual Behavior
However, for the Channel Islands example, it produces a looping error in makePolygons.  I have not dug deeper to figure out why.

```
node scripts/debugExample.js examples/Channel-Islands.geojson    
segmentation: 7.774ms
index: 3.700ms
Error: Looping through the same path
    at _loop_2 (/Users/twelch/src/union-subdivided-polygons/dist/src/makePolygons.js:46:27)
    at _loop_1 (/Users/twelch/src/union-subdivided-polygons/dist/src/makePolygons.js:101:27)
    at makePolygons (/Users/twelch/src/union-subdivided-polygons/dist/src/makePolygons.js:162:9)
    at /Users/twelch/src/union-subdivided-polygons/scripts/debugExample.js:54:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.createConnection (/Users/twelch/src/union-subdivided-polygons/node_modules/slonik/dist/src/factories/createConnection.js:96:18)
polygonize: 9.998ms
union features total: 22.168ms
```

If you pass an originalIdProperty of `_oid` per usual, it works fine.  Since that's the normal use, I expect the scenario of not passing a property just hasn't been tried in a while?  Note that the property is now passed as an additional argumen tto debugExample.

```
node scripts/debugExample.js examples/Channel-Islands.geojson _oid
segmentation: 4.268ms
index: 0.388ms
polygonize: 0.845ms
union features total: 6.190ms
```

**Comment by twelch** [comment]
https://seasketch.slack.com/archives/C02PXCND3/p1617838816018200
